networks:
  app-network:
    driver: bridge

services:
  auth-api:
    container_name: auth-api
    image: auth-api
    build:
      context: ./auth-api
    environment:
      - AUTH_API_PORT=8081
      - USERS_API_ADDRESS=http://users-api:8083
      - JWT_SECRET=myfancysecret
    ports:
      - "8081:8081"
    depends_on:
      - users-api
    networks:
      - app-network

  log-message-processor:
    container_name: log-message-processor
    image: log-message-processor
    build:
      context: ./log-message-processor
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel
    ports:
      - "8084:8084"    
    depends_on:
      - redis
    networks:
      - app-network

  todos-api:
    container_name: todos-api
    image: todos-api
    build:
      context: ./todos-api
    environment:
      - TODO_API_PORT=8082
      - JWT_SECRET=myfancysecret
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel
    ports:
      - "8082:8082"
    depends_on:
      - redis
      - log-message-processor
    networks:
      - app-network

  users-api:
    container_name: users-api
    image: users-api
    build:
      context: ./users-api 
    environment:
      - JWT_SECRET=myfancysecret
      - SERVER_PORT=8083
    ports:
      - "8083:8083"
    networks:
      - app-network

  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ./frontend
    depends_on:
      - auth-api
      - todos-api
    ports:
      - "80:80"
    networks:
      - app-network

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
